services :

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=yourpassword
      - DATABASE_NAME=yourdatabase
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./adminer_logs:/var/log/adminer

  endlessh:
    image: lscr.io/linuxserver/endlessh:latest
    container_name: endlessh
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Frankfurt
    volumes:
      - ./logs:/config/logs/endlessh
    ports:
      - 22:2222
    restart: unless-stopped

volumes:
   db_data: 
   adminer_logs:
